import React from 'react';

import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';

import Header from '@/features/header/component/Header';
import { authOptions } from '@/lib/auth';
import ClientProviders from '@/providers/ClientProviders';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<React.ReactNode> {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      {/* Favicon */}
      <link
        rel='icon'
        href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>'
      />

      <body className='flex h-screen w-screen flex-col'>
        <ClientProviders session={session}>
          <Header />
          <main className='flex-grow overflow-auto bg-[url(/assets/light-bg.svg)] bg-cover bg-repeat dark:bg-[url(/assets/dark-bg.svg)]'>
            {children}
          </main>
        </ClientProviders>
      </body>
    </html>
  );
}
