import React from 'react';

import type { Metadata } from 'next';

import ClientProviders from '@/providers/ClientProviders';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactNode {
  return (
    <html lang='en'>
      {/* Favicon */}
      <link
        rel='icon'
        href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>'
      />
      <ClientProviders>
        <body className={''}>{children}</body>
      </ClientProviders>
    </html>
  );
}
